version: "2.14.1"

services:
  database:
    image: postgres
    container_name: autorenter_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=postgresdb
      - POSTGRES_DB=autorenter_db
    volumes:
      - pgdata:/data/postgres
    network_mode: host

  app:
    build: .
    image: autorenter
    container_name: autorenter-api
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host
    # links:
    #   - database
    # depends_on:
    #   - database

volumes:
  pgdata:
    driver: local