version: "3"

services:
  database:
    image: postgres
    container_name: rentx_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    networks:
      - mynetwork

  app:
    build: .
    container_name: rentx
    image: rentx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app # this directory must be the same as the one referenced in the workdir of the dockerfile
    networks:
      - mynetwork
    depends_on:
      - database
    links:
      - database

networks:
  mynetwork:

volumes:
  pgdata:
    driver: local